
all:
	g++ -o md main.cpp ThermodynamicVariable.cpp coordinates.cpp utils.cpp Rdf.cpp Velocity.cpp triclinicbox.cpp PdbFile.cpp Thermostat.cpp NeighborList.cpp -O3 -I. -I/usr/local/include -std=gnu++11 -Wall -lxdrfile -fopenmp
